services:
  api:
    build:
      context: api
      additional_contexts:
      - config=config
    container_name: lucos_configy
    ports:
      - $PORT:$PORT
    environment:
      - PORT
    image: lucas42/lucos_configy
    restart: always
